# Exercicio Licitações

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('/content/drive/MyDrive/Análise Dados - Programaria/licitacoes.csv', encoding='latin-1', sep=';')

### Identifique qual coluna possui valores faltantes

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Número Licitação          15336 non-null  int64
 1   Código UG                 15336 non-null  int64
 2   Nome UG                   15336 non-null  object
 3   Código Modalidade Compra  15336 non-null  int64
 4   Modalidade Compra         15336 non-null  object
 5   Número Processo           15336 non-null  object
 6   Objeto                    15336 non-null  object
 7   Situação Licitação        15336 non-null  object
 8   Código Órgão Superior     15336 non-null  int64
 9   Nome Órgão Superior       15336 non-null  object
 10  Código Órgão              15336 non-null  int64
 11  Nome Órgão                15336 non-null  object
 12  UF                        15336 non-null  object
 13  Município                 15336 non-null  object
 14  Data Resultado Compra     15336 non-null  object
 15  Data Abertura             4688 non-null   object
 16  Valor Licitação           15336 non-null  object
dtypes: int64(5), object(12)
memory usage: 2.0+ MB

###  Identifique o tipo de dados desta coluna

In [ ]:
dados.groupby('Data Abertura', dropna=False).nunique()

,Número Licitação,Código UG,Nome UG,Código Modalidade Compra,Modalidade Compra,Número Processo,Objeto,Situação Licitação,Código Órgão Superior,Nome Órgão Superior,Código Órgão,Nome Órgão,UF,Município,Data Resultado Compra,Valor Licitação
Data Abertura,,,,,,,,,,,,,,,,
01/06/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
01/10/2018,5,5,5,2,2,5,5,2,4,4,5,5,3,3,5,5
01/11/2018,27,26,26,3,3,29,29,7,11,11,19,19,13,17,14,26
01/12/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
02/04/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31/07/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
31/08/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
31/10/2018,27,31,31,3,3,33,33,6,11,11,22,22,13,18,17,28
31/12/2018,9,6,6,2,2,9,9,2,4,4,6,6,6,6,1,9
NaN,1512,1708,1691,8,8,9687,9658,15,32,32,201,201,28,431,26,6861

In [ ]:
dados['Data Abertura'].isnull().value_counts()

Data Abertura
True     10648
False     4688
Name: count, dtype: int64

### Substitua os valores faltantes pelo mesmo formato

In [ ]:
datas_inexistentes = '01/01/1900'

In [ ]:
dados[dados['Data Abertura'].isnull()] = datas_inexistentes

In [ ]:
dados['Data Abertura'].isnull().value_counts()

Data Abertura
False    15336
Name: count, dtype: int64

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15336 entries, 0 to 15335
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Número Licitação          15336 non-null  object
 1   Código UG                 15336 non-null  object
 2   Nome UG                   15336 non-null  object
 3   Código Modalidade Compra  15336 non-null  object
 4   Modalidade Compra         15336 non-null  object
 5   Número Processo           15336 non-null  object
 6   Objeto                    15336 non-null  object
 7   Situação Licitação        15336 non-null  object
 8   Código Órgão Superior     15336 non-null  object
 9   Nome Órgão Superior       15336 non-null  object
 10  Código Órgão              15336 non-null  object
 11  Nome Órgão                15336 non-null  object
 12  UF                        15336 non-null  object
 13  Município                 15336 non-null  object
 14  Data Resultado Compra     15336 non-null  object
 15  Data Abertura             15336 non-null  object
 16  Valor Licitação           15336 non-null  object
dtypes: object(17)
memory usage: 2.0+ MB

In [ ]:
dados.groupby('Data Abertura', dropna=False).nunique()

,Número Licitação,Código UG,Nome UG,Código Modalidade Compra,Modalidade Compra,Número Processo,Objeto,Situação Licitação,Código Órgão Superior,Nome Órgão Superior,Código Órgão,Nome Órgão,UF,Município,Data Resultado Compra,Valor Licitação
Data Abertura,,,,,,,,,,,,,,,,
01/01/1900,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
01/06/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
01/10/2018,5,5,5,2,2,5,5,2,4,4,5,5,3,3,5,5
01/11/2018,27,26,26,3,3,29,29,7,11,11,19,19,13,17,14,26
01/12/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31/01/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
31/07/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
31/08/2018,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
31/10/2018,27,31,31,3,3,33,33,6,11,11,22,22,13,18,17,28
31/12/2018,9,6,6,2,2,9,9,2,4,4,6,6,6,6,1,9

# Exercicio Municipios Brasileiros

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [6]:
dados2 = pd.read_csv('/content/drive/MyDrive/Análise Dados - Programaria/municipios_brasileiros.csv')

In [7]:
dados2.head()

,codigo_ibge,nome_municipio,codigo_uf,uf,estado,capital,latitude,longitude
0,5200050,Abadia de Goiás,52,GO,Goiás,0,-16.75730,-49.4412
1,3100104,Abadia dos Dourados,31,MG,Minas Gerais,0,-18.48310,-47.3916
2,5200100,Abadiânia,52,GO,Goiás,0,-16.19700,-48.7057
3,3100203,Abaeté,31,MG,Minas Gerais,0,-19.15510,-45.4444
4,1500107,Abaetetuba,15,PA,Pará,0,-1.72183,-48.8788